name: to_do_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  table_calendar: ^3.0.0
  intl: ^0.17.0
  provider: ^6.1.2
  standard_searchbar: ^2.1.1
  pin_code_fields: ^8.0.1
  introduction_screen: ^3.0.2
  intro_slider: ^4.2.1
  cloud_firestore: ^5.2.0
  firebase_auth: ^5.1.3
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/
