// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1rmoO9oP6ETq0dGud-yRzjiwkJXE3Moc',
    appId: '1:924243321702:web:371ec366aa90a7e3e5dea7',
    messagingSenderId: '924243321702',
    projectId: 'todo-app-51397',
    authDomain: 'todo-app-51397.firebaseapp.com',
    storageBucket: 'todo-app-51397.appspot.com',
    measurementId: 'G-TR5EK2W4F7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJnGp5YEwon3OAwTBbr2GE2Iz6fE0F8jw',
    appId: '1:924243321702:android:491907e64c7a59e3e5dea7',
    messagingSenderId: '924243321702',
    projectId: 'todo-app-51397',
    storageBucket: 'todo-app-51397.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgcg0WhG8Bt66rUzl67kajeLmliHUUkZw',
    appId: '1:924243321702:ios:b4883478c20d6235e5dea7',
    messagingSenderId: '924243321702',
    projectId: 'todo-app-51397',
    storageBucket: 'todo-app-51397.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgcg0WhG8Bt66rUzl67kajeLmliHUUkZw',
    appId: '1:924243321702:ios:b4883478c20d6235e5dea7',
    messagingSenderId: '924243321702',
    projectId: 'todo-app-51397',
    storageBucket: 'todo-app-51397.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1rmoO9oP6ETq0dGud-yRzjiwkJXE3Moc',
    appId: '1:924243321702:web:7034dd1afba8f27de5dea7',
    messagingSenderId: '924243321702',
    projectId: 'todo-app-51397',
    authDomain: 'todo-app-51397.firebaseapp.com',
    storageBucket: 'todo-app-51397.appspot.com',
    measurementId: 'G-HMG3PJ2Q0Z',
  );
}
